name: finamp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.6.19+40

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  json_annotation: ^4.8.0
  chopper: ^7.0.3
  get_it: ^7.2.0
  just_audio: ^0.9.35
  audio_service: ^0.18.12
  audio_session: ^0.1.16
  rxdart: ^0.27.7
  simple_gesture_detector: ^0.2.0
  path_provider: ^2.0.14
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  file_sizes: ^1.0.6
  logging: ^1.1.1
  collection: ^1.18.0
  clipboard: ^0.1.3
  file_picker: ^5.2.8
  permission_handler: ^11.0.0
  provider: ^6.0.5
  uuid: ^3.0.7
  infinite_scroll_pagination: ^4.0.0
  flutter_sticky_header: ^0.6.5
  device_info_plus: ^9.0.3
  package_info_plus: ^4.1.0
  octo_image: ^2.0.0
  share_plus: ^7.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  path: ^1.8.2
  android_id: ^0.3.5
  intl: ^0.18.0
  auto_size_text: ^3.0.0
  palette_generator:
    git:
      url: https://github.com/jmshrv/packages.git
      branch: pallete-generator-isolates
      ref: 4992c3b
      path: packages/palette_generator
  flutter_tabler_icons:
    git:
      url: https://github.com/jmshrv/flutter_tabler_icons.git
      branch: update_icons
      ref: 3ae0836
  flutter_riverpod: ^2.3.4
  # locale_names:
  #   git:
  #     url: https://github.com/Mantano/locale_names.git
  #     ref: 74e55fd
  locale_names:
    git:
      url: https://github.com/lamarios/locale_names.git
      ref: cea057c220f4ee7e09e8f1fc7036110245770948
  flutter_vibrate: ^1.3.0
  flutter_downloader: ^1.11.5
  mini_music_visualizer: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  chopper_generator: ^7.0.1
  hive_generator: ^2.0.0
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/finamp.png
  #   - images/a_dot_ham.jpeg

  generate: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca-Thin.ttf
          weight: 100
        - asset: assets/fonts/LexendDeca-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/LexendDeca-Light.ttf
          weight: 300
        - asset: assets/fonts/LexendDeca-Regular.ttf
          weight: 400
        - asset: assets/fonts/LexendDeca-Medium.ttf
          weight: 500
        - asset: assets/fonts/LexendDeca-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/LexendDeca-Bold.ttf
          weight: 700
        - asset: assets/fonts/LexendDeca-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/LexendDeca-Black.ttf
          weight: 900

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_combined.png"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  adaptive_icon_background: "#000B25"
  remove_alpha_ios: true
